# Example configuration parameters for PopSyCLE pipeline
# Loaded by `run_on_slurm:load_popsycle_config`

radius_cut: 2
obs_time: 1095
n_obs: 10
theta_frac: 2
blend_rad: 0.75
isochrones_dir: /project/projectdirs/uLens/code/src/PopSyCLE_isochrones
bin_edges_number: None
BH_kick_speed: 100
NS_kick_speed: 350
filter_name: r
red_law: Schlafly11